### ISSUE TITLE
Transformation code may change under opencv4?

### ISSUE THREAD

**Issue by Fly-dream12** [hukaixuan19970627/DOTA_devkit_YOLO#1]
In the newest opencv version, the theta obtained by cv2.minAreaRect is (0,90], soshould this script YOLO_transform be revised ?

**Comment by hukaixuan19970627** [comment]
I prefer the old version. Because I don't need to change the code.

**Comment by hukaixuan19970627** [comment]
I update the [yolov5-obb](https://github.com/hukaixuan19970627/yolov5_obb)，it supports the newest opencv version.
