### ISSUE TITLE
ImgSplit.py和ImgSplit_multi_process.py的区别

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/DOTA_devkit_YOLO#10]
首先很感谢大佬写的这个项目！已经给项目星星了^ ^
然后就是我看到项目里有ImgSplit.py和ImgSplit_multi_process.py
还有ResultMerge.py和ResultMerge_multi_process.py
SplitOnlyImage.py和SplitOnlyImage_multi_process.py
这些有啥区别呢 要使用的话 应该使用哪一个
还有dota-v1.5_evaluation_task1.py和dota-v1.5_evaluation_task2.py
dota_evaluation_task1.py和dota_evaluation_task2.py
分了1和2的意思是。。

**Comment by hukaixuan19970627** [comment]
multi_process 多进程，切割大量图片的时候可以减少运行时间，进程数视系统内存而定，设得太大容易爆内存导致进程崩溃。
Split切割图片以及图片对应的labels，SplitOnlyImage只切割图片，前者用于处理训练集和验证集，后者用于处理没有标注的测试集。
task1是dota的旋转检测任务，因此要求box的数据形式为poly，task2是dota的水平检测任务，要求box的数据形式为x1y1x2y2.
v1和v1.5对应dota数据集的两个版本，其实就是评估的类别数量不同

**Comment by shenhaibb** [comment]
谢谢大佬！

> multi_process 多进程，切割大量图片的时候可以减少运行时间，进程数视系统内存而定，设得太大容易爆内存导致进程崩溃。 Split切割图片以及图片对应的labels，SplitOnlyImage只切割图片，前者用于处理训练集和验证集，后者用于处理没有标注的测试集。 task1是dota的旋转检测任务，因此要求box的数据形式为poly，task2是dota的水平检测任务，要求box的数据形式为x1y1x2y2. v1和v1.5对应dota数据集的两个版本，其实就是评估的类别数量不同
