### ISSUE TITLE
Error running the training file；Multi-distributed training

### ISSUE THREAD

**Issue by Alice-cmd666** [hukaixuan19970627/DOTA_devkit_YOLO#11]
I have two video cards. I changed the parameters of the corresponding video card during training, but the code of the training file runs incorrectly.
subprocess.CalledProcessError: Command '['/root/miniconda3/envs/yolov5/bin/python', '-u', 'train.py', '--local_rank=1', '--sync-bn']' returned non-zero exit status 1.

**Comment by hukaixuan19970627** [comment]
```
$   python -m torch.distributed.launch --nproc_per_node 2 train.py --sync-bn --device 0,1
```
Is this command cause the error?
