### ISSUE TITLE
opencv表示法的范围

### ISSUE THREAD

**Issue by xubaiqi** [hukaixuan19970627/DOTA_devkit_YOLO#17]
请问detect:θ计算出现异常，当前数据为：68.0000000000000000, 228.0000000000000000, 0.0001779465237632, 0.0000000000000000, 31.0;超出opencv表示法的范围：[-90,0)

**Comment by hukaixuan19970627** [comment]
你是指yolov5_obb项目吗，这个项目在今年1月份就大更新过一次，不会出现超出范围的报错提示，如果你用的是去年的老版本，那么记得更新一下代码
