### ISSUE TITLE
根据labels绘制边框的问题

### ISSUE THREAD

**Issue by sangsasi** [hukaixuan19970627/DOTA_devkit_YOLO#4]
博主您好。请问我按您给的代码制作yolo数据集然后绘制边框，得到的边框是平行四边形的，我想可能是在反归一化的时候比例出现问题，但是从您绘制的图像来看并没有出现这个问题。
           poly[:, 0] = poly[:, 0] * img_w
            poly[:, 1] = poly[:, 1] * img_h

**Comment by hukaixuan19970627** [comment]
可以参考下这篇文章
https://zhuanlan.zhihu.com/p/385701722
我这个月在外边，无法更改以及测试代码

**Comment by hukaixuan19970627** [comment]
不过最好确保图像height=width，yolov5那个项目数据预处理有点问题，height！=width的话，可能labels会有偏移现象

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb
我更新了一版代码，重构了一遍yolo预处理的逻辑，这个问题以后不会再出现了。
不过DOTA_devkit_YOLO这个repo也就没啥用了，poly与rbox之间的转换由内部代码自动完成
