### ISSUE TITLE
将图像转成height=width的问题

### ISSUE THREAD

**Issue by hushuai1** [hukaixuan19970627/DOTA_devkit_YOLO#5]
您在文章里面提到过这个：
![image](https://user-images.githubusercontent.com/43898397/128111130-c7f3bb3f-1961-4961-9dba-9ae3024260aa.png)
我的数据集图像大小是  1280x720   设置  subsize  = 1280以后运行代码并没有pad，请问您这个pad功能是哪部分代码实现的呢

**Comment by hukaixuan19970627** [comment]
参数padding默认是置为True的，你可以全局搜索padding找到对应代码

**Comment by hushuai1** [comment]
感谢，我在ImgSplit_multi_process.py这个文件中找到了相关代码
