### ISSUE TITLE
图像数据归一化的问题

### ISSUE THREAD

**Issue by root12321** [hukaixuan19970627/DOTA_devkit_YOLO#6]
![image](https://user-images.githubusercontent.com/28287748/128995362-e7a66c83-47fe-4e1f-ac22-1bc5cb76dfa6.png)
这里的
x[:, 1] - x[:, 3] / 2
x[:, 2] - x[:, 4] / 2
x[:, 1] + x[:, 3] / 2
x[:, 2] + x[:, 4] / 2
是你对长边表示法转poly的过程，但是我觉得这个转换的过程是有问题的，如下图：
![731b72ab9bbb02fe5dd429d00553053](https://user-images.githubusercontent.com/28287748/128995642-a2957bb4-2a3f-4d7a-8e84-dce5e7601251.jpg)
可以看到长边表示法并不能确定长边对应的是x坐标还是y坐标，这就会导致转的poly其实是有问题的，我这个理解不知道对不对？

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/yolov5_obb
我更新了一版代码，重构了一遍yolo预处理的逻辑，这种疑虑以后不会再出现了，数据在预处理过程中全程以poly形式进行运算。
