### ISSUE TITLE
A problem about data prepare 

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/DOTA_devkit_YOLO#7]
![image](https://user-images.githubusercontent.com/54108453/133646203-4e5f9d09-2d3b-4abc-8068-ec0ef4e24e89.png)
![image](https://user-images.githubusercontent.com/54108453/133646985-48494a1a-85db-46ba-a388-b9e60456f6fd.png)
![image](https://user-images.githubusercontent.com/54108453/133647972-e45c3840-320a-497d-9d54-567a28bb6495.png)

I applied YOLO_Transform.py to convert data format and draw objects. However, the oriented bounding boxes probably have some deviations, when the objects have large size or angle.

**Comment by hukaixuan19970627** [comment]
Well，the image must meets HEIGHT = WIDTH

**Comment by hukaixuan19970627** [comment]
I fixed this bug in the latest version. 
https://github.com/hukaixuan19970627/yolov5_obb
