### ISSUE TITLE
对label进行转换

### ISSUE THREAD

**Issue by nutalk** [hukaixuan19970627/DOTA_devkit_YOLO#8]
https://github.com/hukaixuan19970627/DOTA_devkit_YOLO/blob/07d6987da8199a5917a672e9e98373597e008b9f/SplitOnlyImage.py#L7

你好，感谢你的工作，我看这部分只对图片进行切分，并没有对label进行转换。这部分代码有吗？

**Comment by hukaixuan19970627** [comment]
SplitOnlyImage.py只切图像不切label，这个是用来切没有标注的测试集的，切割训练集验证集的话你应该使用ImgSplit.py
