### ISSUE TITLE
Loss 降不下去

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/DOTA_devkit_YOLO#9]
![image](https://user-images.githubusercontent.com/73689702/143348924-3e7cff6a-205b-432d-ab0f-dd22ba94dbbe.png)
batch_size = 4  lr = 0.01 150个epoch Loss 从1 降低到0.5 训练速度很慢，所以就将batch_size 调大了
batch_size = 64 lr =0.16 300个epoch Loss从1降低到0.4

**Comment by hukaixuan19970627** [comment]
接着当前权重把mosaic 或mixup等多样本数据增强关闭，继续训练还能接着收敛
